version: '3.9'

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db

    restart: always

    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - spring-ai-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "8050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - postgres

    networks:
      - spring-ai-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  spring-ai-network:
    driver: bridge