spring.application.name=Securitytest

server.port=8099
spring.devtools.add-properties=false

#spring.profile=default
spring.security.user.name=ramu
spring.security.user.password=ramu

spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

